CREATE DATABASE CSP_TUTORIALS_2018368;
USE CSP_TUTORIALS_2018368;
CREATE TABLE Artist(
	artID INT,
    artName VARCHAR(255) NOT NULL,
    
    CONSTRAINT pk_Art_artID PRIMARY KEY (artID),
    CONSTRAINT chk_Art_artName UNIQUE (artName)
);
DESCRIBE Artist;

CREATE TABLE CD(
	cdID INT NULL NULL,
    cTitle VARCHAR(20),
    cPrice DOUBLE,
    cGenre VARCHAR(20),
    cNumberOfTracks INT,
    
    CONSTRAINT pk_cd_cID PRIMARY KEY (cID)
    
);

DESCRIBE CD;
SHOW TABLES;

ALTER TABLE CD ADD COLUMN artID INT NOT NULL;
ALTER TABLE CD ADD CONSTRAINT fk_Art_CD_artID FOREIGN KEY (artID) REFERENCES Artist (artID);

CREATE TABLE Track(
	trID INT,
    trTitle VARCHAR(20) NOT NULL,
    trTime TIME,
    
    CONSTRAINT tr_tID_pk PRIMARY KEY(trID)
);

DESCRIBE Track;

CREATE TABLE CD_Track(
	cdID INT,
    trID INT,
    
    CONSTRAINT fk_CD_Track_cdID  FOREIGN KEY (cdID) REFERENCES CD (cdID),
    CONSTRAINT fk_CD_Track_trID  FOREIGN KEY (trID) REFERENCES Track (trID),
    
	CONSTRAINT pk_cdtrack_cIDtrID PRIMARY KEY(cdID,trID)
);

DESCRIBE CD_Track;
SHOW CREATE TABLE CD;